### ISSUE TITLE
Runoff interpolation issue when using constant runoff (CORE2)

### ISSUE THREAD

**Issue by FinnHeu** [FESOM/fesom2#138]
Hello everyone, 

I think I found a bug when using constant runoff, in my case CORE2. The interpolation onto the model grid produces some weird results that does not look like the original runoff data at all. When looking at the Kara Sea or the Amazon runoff the large runoff in the original runoff file vanishes in the interpolated field and instead there is very weak and randomly distributed runoff all over the ocean. 

![runoff_amazon](https://user-images.githubusercontent.com/57488986/122010306-454a2e80-cdbb-11eb-9bdc-6d6ec76c4bb7.png)

![runoff_kara_sea](https://user-images.githubusercontent.com/57488986/122010318-4a0ee280-cdbb-11eb-9745-1bb5bd1e970d.png)

Using runoff_data_source = 'CORE2' in namelist.forcing triggers a special case in gen_surface_forcing.F90 where read_other_netCDF is called to load and interpolate the runoff.  

```
! runoff    
      if (runoff_data_source=='CORE1' .or. runoff_data_source=='CORE2' ) then
         ! runoff in CORE is constant in time
         ! Warning: For a global mesh, conservative scheme is to be updated!!
         call read_other_NetCDF(nm_runoff_file, 'Foxx_o_roff', 1, runoff, .false., mesh) 
         runoff=runoff/1000.0_WP  ! Kg/s/m2 --> m/s
      end if
```
Maybe there is something wrong in the interpolation routine? I initially tried to load regional wind anomaly fields using the subroutine read_other_netcdf and those were randomly scattered all over the grid as well in the interpolated field. 
 
I ran the model on CORE grid for two month with daily output. The runoff output is constant in time.
In namelist.forcing i used:

```
&nam_sbc
...
   nm_runoff_file     ='/work/ollie/clidyn/forcing/JRA55-do-v1.4.0/CORE2_runoff.nc'
   runoff_data_source ='CORE2'	!Dai09, CORE2
   runoff_climatology =.false.
...
/
```

Any ideas whether I did something wrong or if this is a bug are very much appreciated.

Best, 
Finn

**Comment by koldunovn** [comment]
Hi @FinnHeu 
First thing I would check is if other fields look OK as well and there is no error with rotation of the grid during the post processing. Can you give me the path to your namelists?

**Comment by FinnHeu** [comment]
Hi @koldunovn 
the path to the nameless is: /home/ollie/fheukamp/fesom2/CORE/work
E.g. for a_ice the same thing happens...

I just saw that force_rotation=.false. in my namelist.config: 
```
&geometry
cartesian=.false.
fplane=.false.
cyclic_length=360	![degree]
rotated_grid=.true.     !option only valid for coupled model case now
force_rotation=.false.
alphaEuler=50.          ![degree] Euler angles, convention:
betaEuler=15.           ![degree] first around z, then around new x,
gammaEuler=-90.         ![degree] then around new z.
/
```  

Might this cause the issue?

**Comment by patrickscholz** [comment]
@koldunov & @FinnHeu 
The model should still complain when the rotation flag doesn't fit the mesh! The model should break with and error message that tells you what to do. Since this didnt happen i guess the rotation flag might not be the issue

**Comment by koldunovn** [comment]
The model is fine, as Patrick said, it would not run with the wrong rotation flag. It's in the plotting then. 

Before there were a lot of confusion with mesh rotation because there were rotated and unrotated meshes floating around. We made a decision to use only unrotated meshes as defaults from the last year, and get rid of the rotated ones. You now use core mesh that is quite old `FESOM2_minimum_input/mesh/CORE/` and rotated (this is why you have `force_rotation=.false.`). Please switch to the standard core mesh (`/work/ollie/projects/clidyn/FESOM2/meshes/core2/`), that is unrotated (you would need to change `force_rotation=.true.`).

I guess in your plotting routines the mesh considered to be unrotated by default (e.g. in pyfesom2 `load_mesh`, `abg` would be `=[0,0,0]`), that's why you get wrong coordinates.

This is our most favorite bug, you don't count as a real FESOM user before you hit that, so congratulations! ;)

**Comment by FinnHeu** [comment]
Alright, thanks a lot for your support! I'll go ahead and use the new CORE mesh then.
