### ISSUE TITLE
Changeing field in restart.oce file

### ISSUE THREAD

**Issue by JanStreffing** [FESOM/fesom2#25]
Say I want to crate an experiment where I reduce the temperature in the Labrador sea to simulate a restart from a little ice age. I'm looking for the simplest solution for a master student. 

I found that with cdo setgrid,/work/ollie/jstreffi/input/fesom2/mesh_CORE2_finaltopo_mean/CORE2_finaltopo_mean.nc restartin.nc restartout.nc I can turn 2d generic files into unstructured files that can be used for a wide varity of cdo commands. 

However this works only with the 2d ice restarts that contain only one grid. Is there a similar process & file for 3d data? Or should I forget trying to make cdo work and just do it in python?

**Comment by JanStreffing** [comment]
Okay thinking about it clearly python is easier.. nvm.

**Comment by koldunovn** [comment]
You can use this script as a starting point:
https://github.com/FESOM/fesom2/blob/master/view/scripts/select_restart.py

**Comment by helgegoessling** [comment]
> Is there a similar process & file for 3d data?
The newest FESOM2 output has the metadata included which is required to do the exact same thing with 3D data. You can use the same grid description file, because the vertical information is then part of the FESOM2 files. For older FESOM2 output, you would need to use the NCOs and do something like `ncatted -a axis,temp,c,c,"T-Z" temp.fesom.1958.nc` first to add information about the axes and their order in the file.

> Or should I forget trying to make cdo work and just do it in python?
For that task I would not use the CDOs because, even if they work, they might modify the metadata of the restart file in such a way that FESOM2 does not like for a restart file. A more straightforward way is to open the netcdf file in Python/R/whatever in write mode, and then just manipulate the data entries you want to manipulate. I've done that in the past to introduce initial-state perturbations.

> Say I want to crate an experiment where I reduce the temperature in the Labrador sea to simulate a restart from a little ice age. I'm looking for the simplest solution for a master student.
Physically, this might not be such a trivial task. I guess you'd need to come up with some kind of vertical cooling-profile (and lateral transition zone) that does not lead to crazy initial shocks (e.g., due to strongly unstable initial stratification), and at the same time is more or less meaningful to represent the "little ice age". But I'm just speculating...

**Comment by JanStreffing** [comment]
Hello Helge, thank you for the feedback, we will use python, starting from a script that is part of the AWI-ESM2 Ice sheet coupling by Lars Ackermann. I will keep the potential physical difficulties in the back of my mind.

**Comment by koldunovn** [comment]
@JanStreffing In the past I had problems when netCDF version that python uses was not the same as the version FESOM2 is compiled with, so be aware of potential troubles here.

**Comment by JanStreffing** [comment]
Trouble in terms of python not being able to deal with the FESOM2 data or FESOM2 not playing ball with the resulting restart file?

**Comment by koldunovn** [comment]
FESOM2 not playing ball with the resulting restart file. Reading with python is usually not a problem.
