### ISSUE TITLE
Impact of "recent" kpp_Kv0 update

### ISSUE THREAD

**Issue by JanStreffing** [FESOM/fesom2#32]
As noted by @mandresm on slack, there was a "recent" change to the namelist.cvmix parameter kpp_Kv0 https://github.com/FESOM/fesom2/commit/36ea7ce390c82b9283adeb8cb56ba54097343eab

The the commit message reads: 
> change back to traditional value 0.05 --> 0.005 of kpp maximum diffusivity of shear driven mixing --> suggestion by Qiang --> reduced biases

I branched off for the AWICM3 DECK simulations before this commit and so used the old value. Could you illuminate what type and strength of bias reduction you saw? @qiangclimate @patrickscholz

**Comment by patrickscholz** [comment]
@JanStreffing In basical i just synchronised here the value that was already in use since a while in the standard (old FESOM1.4,mix_scheme='KPP') mixing scheme under the parameter diff_sh_limit (in namelist.oce). The namelist.cvmix is only  in use when you explicitly use one of the cvmix mixing schemes, which mean  mix_scheme='cvmix_KPP', 'cvmix_PP', 'cvmix_TKE' ...
Anyway the kpp_Kv0 or diff_sh_limit only matters when you use constant background diffusivity, but as default we choosed to have the non-konstant, lat and depth dependent background diffusivitiy of qiang. The switch here is either Kv0_const=.false./.true. in namelist.oce in case you use the old KPP/PP mixing scheme or kpp_use_nonconstKvb= .true./.false. when you use one of the cvmix mixing schemes.   

If i remember well, qiang claimed that a kpp_Kv0 of 0.05 is way strong a messes things up especially in the Arctic Ocean. I think he or one of his Phd did some runs regarding this.

**Comment by qiangclimate** [comment]
I suppose that "diff_sh_limit" is discussed here, rather than kpp_Kv0.
A short answer: the test in April showed that the value 0.05 or 0.005 change the model results very little. (which is a bit strange, but we did not go deeper to find out why the sensitivity is so small). 
Anyway, when we saw that there is no large impacts, why not use the value suggested in literature before, that is, 0.005. I think this is the reason why Patrick changed the value back to traditional in the model.

**Comment by JanStreffing** [comment]
> The namelist.cvmix is only in use when you explicitly use one of the cvmix mixing schemes, which mean mix_scheme='cvmix_KPP', 'cvmix_PP', 'cvmix_TKE' ...

I use KPP, see my [namelist.oce](https://github.com/FESOM/fesom2/files/5511596/namelist.oce.txt) and [namelist.cvmix](https://github.com/FESOM/fesom2/files/5511597/namelist.cvmix.txt) 

> Anyway the kpp_Kv0 or diff_sh_limit only matters when you use constant background diffusivity, but as default we choosed to have the non-konstant, lat and depth dependent background diffusivitiy of qiang. The switch here is either Kv0_const=.false./.true. in namelist.oce in case you use the old KPP/PP mixing scheme or kpp_use_nonconstKvb= .true./.false. when you use one of the cvmix mixing schemes.

I have `Kv0_const=.false.` and `kpp_use_nonconstKvb= .true.` so I'm in the clear.

> ... when we saw that there is no large impacts, why not use the value suggested in literature before, that is, 0.005. I think this is the reason why Patrick changed the value back to traditional in the model.

Thank you both for the clarification!

**Comment by qiangclimate** [comment]
according to the namelist, the changes in the usage of mixing scheme based on Monin-Obukhov length was not used, which are specified in namelist now:
use_momix     = .true.     ! switch on/off  !Monin-Obukhov -> TB04 mixing
momix_lat     = -50.0      ! latitidinal treshhold for TB04, =90 --> global
Perhaps hard to change when some runs have already started. 
For future new projects, the change could be taken to reduce the too fresh bias in the Arctic.

**Comment by JanStreffing** [comment]
Hello Qiang,
I take note of this suggestions for future runs. I will say that at the end of the Historic simulations most of the Arctic sees a high salinity bias vs phc3 already.
![image](https://user-images.githubusercontent.com/25483665/99529015-7090aa80-299f-11eb-9d90-b3bfdfc5abbc.png)
