### ISSUE TITLE
Albedo is a diva!

### ISSUE THREAD

**Issue by patrickscholz** [FESOM/fesom2#409]
I made some further test on albedo with the latest fresh refactoring branch and with our standard core2 configuration and realized that on albedo FESOM2 is less stable on albedo. On albedo i needed 64 steps per day so the model doesnt blow up more or less immediately. I made the same test also on ollie with the same fresh refactoring branch there the model is stable at 32 steps per day, like we would expect. 

Initially i thought it might be related to the solver parms but also with our internal Sergey solver its the same!

So far there are no error messages on albedo or anything that could give a hint. 

Only other thing i could imagine would be still an issue with the environment on albedo...?

https://github.com/FESOM/fesom2/blob/5baae1788b02a56354a26ff90908d5c7560437d9/env/albedo/shell#L1-L23

If anybody has an idea what might be problem or in which direction to search...would be a great help!

Mfg

Patrick

**Comment by pgierz** [comment]
Hi @patrickscholz, sure, but that will probably not happen until next week sometime, I have a few other commitments on the (seemingly never-ending) list ;-)

The only hardware and system relevant things I notice in your posted script appear to be linked with inter-node communication: by that I mean the environment variables you are exporting which will tell MPI and the Interconnect (Infiniband or whatever else one has on whatever machine) to behave. Unfortunately you can't squeeze a large grid onto fewer nodes, but you could underpopulated nodes. If the model is blowing up due to communication (some process is sending data around and the other one gives up due to waiting...?), that might be one thing to check. 

Some other thoughts just to have them written down once; a reminder for myself and maybe someone else has some clever ideas that pop up:
* The compilers are different and might have different severities of optimisation
* The compute nodes have a different configuration
* Is it resolution dependent? (can be checked on both machines)

In any case, interesting and something we will keep an eye one. I'll ask also the others in the HPC group, FESOM was one of the benchmarks that was done when they sold us the machine....

**Comment by patrickscholz** [comment]
@pgierz although when i skip the environment variables (which are suggestes by dkrz on Levante) in the albedo jobsubmit script , the problem remains ...

**Comment by pgierz** [comment]
Ok, that is good info to have. If I think of any follow up questions  I'll let you know.
