### ISSUE TITLE
enforcing zero total freshwater flux

### ISSUE THREAD

**Issue by dsidoren** [FESOM/fesom2#41]
wouldn't  it cause a positive freshwater drift when the sea ice melts? 
https://github.com/FESOM/fesom2/blob/86051c80caaea79c7fee7dc68f66dc09707444b6/src/ice_oce_coupling.F90#L177

shall we better enforce the total water_flux be zero?

**Comment by dsidoren** [comment]
I guess it would be a secure choice for long climate spinup

**Comment by patrickscholz** [comment]
@dsidoren  
Im not sure what you mean? in subroutine therm_ice(...) where the freshwater flux is computed we use prec=rain+runo+**_snow*(1.0_WP-A)_**. If we want to balance the total freshwater flux we have to take also +prec_snow*(1.0_WP-a_ice_old) into account at this location, OR NOT ?! Otherwise the volume should drift ?

**Comment by dsidoren** [comment]
ice/snow to water transformation is excluded from the conservation (https://github.com/FESOM/fesom2/blob/86051c80caaea79c7fee7dc68f66dc09707444b6/src/ice_thermo_oce.F90#L381)

Hence the snow over ice is not balanced and enters the freshwater flux after being melted. There will be a drift then.

**Comment by JanStreffing** [comment]
I see the issue was closed. What was the answer to the question posed?

**Comment by dsidoren** [comment]
> I see the issue was closed. What was the answer to the question posed?

it was my confusion, sorry! everything is ok since the ice growth/melt is accounted for a couple of lines later.
