### ISSUE TITLE
FESOM2 too much noise

### ISSUE THREAD

**Issue by PengyangSong** [FESOM/fesom2#49]
Dear FESOM2 developers,
The output velocity of FESOM2 seems to be too perturbed even if it is averaged for 50 years (please check figure 1 the 30S Atlantic section and figure 2 the 1000m horizontal velocity distribution, averaged from 1960-2009). I have checked the plotting routine and I didn't find bugs in them. 

This run is identity with all the settings in the repository and is run with COREII forcing from 1948-2009 (only one cycle). 
namelist dir: /home/ollie/psong/esm-tools/esm-master/fesom-2.0/config_notide1
output dir: /work/ollie/psong/FESOM2/fesom2_NOTIDE_compare1
plot ipynb dir:/home/ollie/psong/post_spy_fesom2/ipynb_code/contour_v/test_linfs.ipynb

![section](https://user-images.githubusercontent.com/72070671/102197775-e5cd9d80-3ec1-11eb-9c82-229524486b8b.png)
![horizontal](https://user-images.githubusercontent.com/72070671/102198637-ec104980-3ec2-11eb-847c-1c7ceec34f79.png)

**Comment by koldunovn** [comment]
@PengyangSong Just to let you know that we are on it, and will try to look at the issue after holidays.

**Comment by koldunovn** [comment]
Hi @PengyangSong . Sorry for the delay with an answer, we had to look at it more closely. For weak currents there is indeed disturbances in the mean field with the current default options. In order to fix this now you can change to:
```
visc_option=7
```
Option 7 does not re-energize the flow as the default option 5, and still provide good levels of viscosity.
To further increase the smoothness, you can change to:
```
gamma1=0.1
```
This will increase viscosity, and drop the energy of the system.

I will play around with this options a bit more, and for the release hope to come up with settings we think are optimal for COREII simulations. 

CC: @dsidoren @patrickscholz

**Comment by koldunovn** [comment]
OK, a bit more info. You can actually keep relatively small `gamma1`, like the default value around 0.03, but increase `gamma0`, that is responsible for the background viscosity. With `gamma0=0.003` the weak currents become much smoother for both `visc_option` 7 and 5. For your tidal applications you should decide what viscosity is best for you, I would assume for research purposes option 7 would be a better choice (or option 5 with `easy_bs_return=1`), since you would like to look at energy effects.

**Comment by PengyangSong** [comment]
@koldunovn Firstly, many thanks to your suggestions on changing the visc_option, I set up new experiments with/without tides using visc_option=7 and the result is better now.
I also want to have a try on bi-Laplacian and bi-harmonic scheme  (visc_option=6 or 4, no other changes made). It works for no-tide run, but for tide runs the model blow up. Do you have any idea on how to tune the variables?
I know you have lots of stuff, so maybe I can tune it myself if you can give me any guidelines.
Kind regards,
Pengyang

**Comment by koldunovn** [comment]
@PengyangSong The most important is to keep `gamma0` around `0.003`, or even higher if you need smoother weak currents.

You can try to play around with  `gamma1` for 6 and 4 by increasing it, so increasing the viscosity. Same is true for `gamma0`, sometimes just a small increase helps. Also turning on `w_split=.true.` might help with stability.

However I would concentrate on options 5 and 7, since in the future those will be our work horses, and all the tuning will be only done for them, keeping other options for research purposes. I can only advice to turn the backscatter off for option 5 during your tide runs (`easy_bs_return=1`)

**Comment by PengyangSong** [comment]
@koldunovn Good day, I found something strange in the code, what is the dimension of variable `vi` and intermediate variable `U_c` in `src/oce_dyn.F90`?
In latest master branch, Line 737: `vi=sqrt(max(gamma0, max(gamma1*sqrt(vi), gamma2*vi))*len)`
while in Line 762：`vi=-dt*sqrt(max(gamma0, max(gamma1*sqrt(vi), gamma2*vi))*len)`
I tried to derive the unit of each variable but it does not lead to a velocity unit for `UV_rhs`, and what I know for sure is `max(gamma0, max(gamma1*sqrt(vi), gamma2*vi)` has the same dimension of velocities.
I speculate for `SUBROUTINE visc_filt_bidiff`, the first half is to calculate something like \nabla^2{UV}, and the second half the same, which forms the biharmonic scheme \nabla^2{vi\nabla^2{UV}}?
Would you please kindly check if there is a bug here? Thanks!

**Comment by koldunovn** [comment]
Just copy here answer from @dsidoren 

Hi all,
gamma0 has the dimension of velocity
```
max(…*len) 
```

hence returns m2/s (viscosity). The dt shall be applied only once there for the whole dissipation term (whether harmonic or biharmonic)

This is not the “exact” viscosity operator (we had an exact implementation as well but did not lead to better results) but a biharmonic filter.

It is easier to understand with the harmonic one. The contribution into RHS on a triangle will be: 
```
visc*(u1+u2+u3-3*u0)/area
visc=max(vi, gamma0*len)*dt
```
I guess everything is alright there. But I will look more carefully.
