### ISSUE TITLE
FESOM2 crashes depending on MESH directory

### ISSUE THREAD

**Issue by ackerlar** [FESOM/fesom2#51]
I have problems running AWI-CM-2.0 on mistral depending on which mesh directory I use for FESOM.

If I take `/pool/data/AWICM/FESOM2/MESHES/CORE2/` I get the following error:
```
666:  ***********************************************************
666:  max. CFL_z =    1.44824733863823       mype =          234
666:  mstep      =            1
666:  glon, glat =   -35.5792148127440       -5.49627545561133     
666:  2D node    =        68061
666:  nz         =            2
666:  ***********************************************************
520:  ***********************************************************
520:  max. CFL_z =    1.82566339425423       mype =           88
520:  mstep      =            1
520:  glon, glat =    73.4124462298563       0.408295191792843     
520:  2D node    =        87261
520:  nz         =            2
520:  ***********************************************************
495:  ___CHECK FOR BLOW UP___________ --> mstep=           1
498:  ___CHECK FOR BLOW UP___________ --> mstep=           1
498:   --STOP--> found eta_n become NaN or <-10.0, >10.0
498:  mype        =           66
498:  mstep       =            1
498:  node        =            1
498:  
498:  eta_n(n)    =                      NaN
498:  d_eta(n)    =   0.000000000000000E+000
```

But if I run the same runscript with this mesh `/mnt/lustre02/work/ab0995/a270029/fesom2.0/meshes/core2/` everything is working fine. Here are the links to the experiments:
`/work/ba0989/a270124/esm-experiments/awicm_pism/ib_notworking01`
`/work/ba0989/a270124/esm-experiments/awicm_pism/ib_working02`

I did not change anything else than mesh directory and used the same esm-tools (bash version). Could this be related #29 ?

I am using a FESOM2.0 version with iceberg model included, but the error also occurs when I turn the iceberg model off. Could anybody clarify what is happening here and why `/pool/data/AWICM/FESOM2/MESHES/CORE2/` is not working? I guess it should be the dafault mesh directory?

**Comment by koldunovn** [comment]
Hi @ackerlar 
Sometimes partitionings done on different machines might cause problems (model blows up without reason). We still investigating this issue, and this might be one reason. 

I also see that meshes has different aux3d.out files, meaning the bathymetry is different. The one in `/pool/data/AWICM/FESOM2/MESHES/CORE2/` has the standard core mesh bathymetry and the one in `/mnt/lustre02/work/ab0995/a270029/fesom2.0/meshes/core2/` modified. Here the question is to @dsidoren if some modification of the mesh was done for coupled setup. 

The situation with different versions of meshes is unsatisfactory, and we are working on making more order in this respect. In particular all supported meshes in the future will be unrotated and put under version control. I see few options on how to proceed.

- Ask what mesh is used by people who run AWI-CM2 on Mistral, @pgierz I think has the most experience. I believe that in order to reproduce Sidorenko et al., 2019 paper you would need to use `/mnt/lustre02/work/ab0995/a270029/fesom2.0/meshes/mesh_CORE2_finaltopo_mean/` (yes another one, that is slightly different from the current standard).
- You can try to repartition the mesh by yourself (https://fesom2.readthedocs.io/en/latest/getting_started/getting_started.html#build-partitioner-executable). This would require to put the mesh in the directory you have write access to. 
- You might try the "unrotated" version of the core mesh, that will be our new standard starting from the next release (`git lfs clone https://gitlab.awi.de/fesom/core2.git`). In this case you should use `force_rotation=.true.` in the `namelist.config`.

The meshes in the `/pool/data/` will be replaced by the standard ones soon, and hope it will reduce the amount of confusion.

**Comment by koldunovn** [comment]
@ackerlar Is it solved now?

**Comment by ackerlar** [comment]
@koldunovn Yes, thank you for your detailed answer!
