### ISSUE TITLE
Order of remaining 2.6 merge requests:

### ISSUE THREAD

**Issue by JanStreffing** [FESOM/fesom2#574]
My current suggestion is:

1. https://github.com/FESOM/fesom2/pull/576
2. https://github.com/FESOM/fesom2/pull/580
3. https://github.com/FESOM/fesom2/pull/377
4. https://github.com/FESOM/fesom2/pull/552
5. https://github.com/FESOM/fesom2/pull/497
6. https://github.com/FESOM/fesom2/pull/571
7. https://github.com/FESOM/fesom2/issues/582
8. https://github.com/FESOM/fesom2/pull/515 check if still needed by then
9. https://github.com/FESOM/fesom2/pull/442 check if still needed by then
10. https://github.com/FESOM/fesom2/pull/120 changes testcase
11. https://github.com/FESOM/fesom2/pull/86 changes testcase
12. https://github.com/FESOM/fesom2/pull/354 (maybe 2.7)

**Comment by trackow** [comment]
Still adding the merge of tag 2.5.0.3_de to the list since this has a couple of changes from the nextGEMS production run that are not in production_DE (https://github.com/FESOM/fesom2/compare/production_DE...2.5.0.3_de).

Namely

- Sergey's solver as default (is de-facto default, to my understanding, but Github tests are not successful)
- changed order of OMP barriers to circumvent frequent network flaps (resulting in most stable IFS-FESOM ever on Levante)
- splitting exchange_nod(sigma_xy, partit) (2x3D field) into 2 separate calls (also related to network flaps)
