### ISSUE TITLE
Default FESOM2 repository

### ISSUE THREAD

**Issue by JanStreffing** [FESOM/fesom2#94]
During our weekly esm_tools meeting the question of the default FESOM2 repository came up. At the moment the default in esm_tools is gitlab, with github as an optional. 

- Is still this reflective of the policy of the FESOM developers? Has the default changed to github?
- Are there plans to automatically sync the two, such that we would not even have to make a choice? 
- Or are there branches on gitlab that are not supposed to go public?

**Comment by koldunovn** [comment]
* The policy is now that the default is github, gitlab is only synced sporadically. We have not decided on gitlab's fate yet. I would close it, but there are people who still do work there, so it should be discussed. 
* Currently it happens by hand, so not very reliable. Even if it would happen automatically, I would still put github as a default, since the number of lucky people who have DKRZ account in this world is fairly limited :)
* I don't know, but I see that not everyone has moved to github jet, maybe they have their reasons.

**Comment by JanStreffing** [comment]
github is default now. closing old issue
